export type LyricLine = {
  measures: number; // Number of measures this line lasts for
  text: string; // Chords can be embedded like [Am]this.
};

export type Song = {
  id: string;
  title: string;
  artist: string;
  lyrics: LyricLine[];
  updatedAt: Date;
  originalKey?: string;
  bpm?: number;
  timeSignature?: string;
  source: 'system' | 'user'; // system: from the app, user: custom song or upload
  // Fields for user-uploaded songs
  userId?: string;
  uploaderName?: string;
  uploaderEmail?: string;
};

const songs: Song[] = [
  {
    id: '1',
    title: 'Starlight Echoes',
    artist: 'Celestial Sound',
    updatedAt: new Date('2023-10-26T10:00:00Z'),
    originalKey: 'C',
    bpm: 120,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { measures: 0, text: "(Intro)" },
      { measures: 2, text: "[Am] [G] [C] [F]" },
      { measures: 2, text: "[C] [G] [Am] [F]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 1)" },
      { measures: 2, text: "[Am]In the quiet of the [G]night," },
      { measures: 2, text: "A single [C]star begins to [F]glow," },
      { measures: 2, text: "[C]Casting shadows in the [G]light," },
      { measures: 2, text: "A silent, [Am]cosmic [F]show." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "We're just [C]echoes in the [G]starlight," },
      { measures: 2, text: "Fading [Am]in and out of [F]view," },
      { measures: 2, text: "[C]Dancing in the pale [G]moonlight," },
      { measures: 2, text: "Just me and [Am]you.[F]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 2)" },
      { measures: 2, text: "Across the [Am]void, a signal [G]sent," },
      { measures: 2, text: "A whispered [C]word, a fleeting [F]thought," },
      { measures: 2, text: "On [C]waves of ether, [G]we're content," },
      { measures: 2, text: "In this [Am]vastness we are [F]caught." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "We're just [C]echoes in the [G]starlight," },
      { measures: 2, text: "Fading [Am]in and out of [F]view," },
      { measures: 2, text: "[C]Dancing in the pale [G]moonlight," },
      { measures: 2, text: "Just me and [Am]you.[F]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Solo)" },
      { measures: 2, text: "[C] [G] [Am] [F]" },
      { measures: 2, text: "[C] [G] [Am] [G]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Outro)" },
      { measures: 4, text: "[C] [G] [Am] [F]... (fade out)" },
    ],
  },
  {
    id: '2',
    title: 'Ocean Drive',
    artist: 'The Midnight Bloom',
    updatedAt: new Date('2025-07-15T10:00:00Z'),
    originalKey: 'G',
    bpm: 100,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { measures: 0, text: "(Intro)" },
      { measures: 2, text: "[G] [D] [Em] [C]" },
      { measures: 2, text: "[G] [D] [Em] [C]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 1)" },
      { measures: 2, text: "[G]Palm trees swaying in the [D]breeze," },
      { measures: 2, text: "[Em]Neon lights are [C]calling me," },
      { measures: 2, text: "[G]Driving down the [D]coastal road," },
      { measures: 2, text: "[Em]Lifting off a [C]heavy load." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "This is the [G]life on [D]Ocean Drive," },
      { measures: 2, text: "Feeling so com[Em]pletely a[C]live," },
      { measures: 2, text: "[G]Underneath the [D]sunset skies," },
      { measures: 2, text: "Reflected [Em]in your loving [C]eyes." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 2)" },
      { measures: 2, text: "[G]The city sleeps, but [D]we're awake," },
      { measures: 2, text: "For [Em]goodness, for [C]heaven's sake," },
      { measures: 2, text: "[G]Let's chase the dawn un[D]til it breaks," },
      { measures: 2, text: "No more [Em]sorrows, no more [C]heartaches." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "This is the [G]life on [D]Ocean Drive," },
      { measures: 2, text: "Feeling so com[Em]pletely a[C]live," },
      { measures: 2, text: "[G]Underneath the [D]sunset skies," },
      { measures: 2, text: "Reflected [Em]in your loving [C]eyes." },
      { measures: 0, text: "" },
      { measures: 0, text: "(Outro)" },
      { measures: 2, text: "[G] [D] [Em] [C]" },
      { measures: 2, text: "[G] [D] [Em] [C]... (fade out)" },
    ],
  },
  {
    id: '3',
    title: 'City of Dreams',
    artist: 'Urban Canvas',
    updatedAt: new Date('2023-11-30T09:00:00Z'),
    originalKey: 'Dm',
    bpm: 95,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
        { measures: 0, text: "(Verse 1)" },
        { measures: 2, text: "The [Dm]rain is washing streets of [C]chrome," },
        { measures: 2, text: "[Bb]Far away from what was [F]home," },
        { measures: 2, text: "A [Dm]thousand faces pass me [C]by," },
        { measures: 2, text: "[Bb]Reflected in a tearful [A]eye." },
        { measures: 0, text: "" },
        { measures: 0, text: "(Chorus)" },
        { measures: 2, text: "In this [Dm]city of our [C]dreams," },
        { measures: 2, text: "[Bb]Nothing's ever what it [F]seems," },
        { measures: 2, text: "[Gm]Chasing flashing, distant [Dm]gleams," },
        { measures: 2, text: "[Bb]Tearing [A]at the very [Dm]seams." },
        { measures: 0, text: "" },
        { measures: 0, text: "(Verse 2)" },
        { measures: 2, text: "The [Dm]subway rattles, a lonely [C]sound," },
        { measures: 2, text: "[Bb]Lost and never to be [F]found," },
        { measures: 2, text: "But [Dm]in the pulse, a rhythm [C]starts," },
        { measures: 2, text: "[Bb]Mending all the broken [A]hearts." },
        { measures: 0, text: "" },
        { measures: 0, text: "(Chorus)" },
        { measures: 2, text: "In this [Dm]city of our [C]dreams," },
        { measures: 2, text: "[Bb]Nothing's ever what it [F]seems," },
        { measures: 2, text: "[Gm]Chasing flashing, distant [Dm]gleams," },
        { measures: 2, text: "[Bb]Living [A]out our wildest [Dm]schemes." },
    ],
  },
  {
    id: '4',
    title: 'Holy Forever',
    artist: 'Chris Tomlin',
    updatedAt: new Date('2024-02-20T11:00:00Z'),
    originalKey: 'A',
    bpm: 72,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { measures: 0, text: "(Intro)" },
      { measures: 2, text: "[A] [F#m] [D] [E]" },
      { measures: 2, text: "[A] [F#m] [D] [E]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 1)" },
      { measures: 2, text: "[A]A thousand generations" },
      { measures: 2, text: "[F#m]Falling down in worship" },
      { measures: 4, text: "To [D]sing the song of [E]ages to the [A]Lamb" },
      { measures: 0, text: "" },
      { measures: 2, text: "[A]And all who’ve gone before us" },
      { measures: 2, text: "And [F#m]all who will believe" },
      { measures: 4, text: "Will [D]sing the song of [E]ages to the [A]Lamb" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "Your name is the [A]highest" },
      { measures: 2, text: "Your name is the [F#m]greatest" },
      { measures: 4, text: "Your name stands a[D]bove them [E]all[A]" },
      { measures: 2, text: "All thrones and do[A]minions" },
      { measures: 2, text: "All powers and po[F#m]sitions" },
      { measures: 4, text: "Your name stands a[D]bove them [E]all[A]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Bridge)" },
      { measures: 2, text: "And the angels [D]cry, [A]Holy" },
      { measures: 2, text: "All creation [F#m]cries, [E]Holy" },
      { measures: 2, text: "You are lifted [D]high, [A]Holy" },
      { measures: 2, text: "Holy for[E]ever" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Verse 2)" },
      { measures: 2, text: "[A]If you’ve been forgiven" },
      { measures: 2, text: "And [F#m]if you’ve been redeemed" },
      { measures: 4, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { measures: 0, text: "" },
      { measures: 2, text: "[A]If you’ve been delivered" },
      { measures: 2, text: "From the [F#m]power of sin" },
      { measures: 4, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Chorus)" },
      { measures: 2, text: "Your name is the [A]highest" },
      { measures: 2, text: "Your name is the [F#m]greatest" },
      { measures: 4, text: "Your name stands a[D]bove them [E]all[A]" },
      { measures: 2, text: "All thrones and do[A]minions" },
      { measures: 2, text: "All powers and po[F#m]sitions" },
      { measures: 4, text: "Your name stands a[D]bove them [E]all[A]" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Bridge)" },
      { measures: 2, text: "And the angels [D]cry, [A]Holy" },
      { measures: 2, text: "All creation [F#m]cries, [E]Holy" },
      { measures: 2, text: "You are lifted [D]high, [A]Holy" },
      { measures: 2, text: "Holy for[E]ever" },
      { measures: 0, text: "" },
      { measures: 0, text: "(Outro)" },
      { measures: 1, text: "Holy for[A]ever" },
    ],
  },
];

export function getSongs(): Song[] {
  return songs;
}

export function getSongById(id: string): Song | undefined {
  return songs.find((song) => song.id === id);
}

    