export type LyricLine = {
  time: number; // in seconds
  text: string; // Chords can be embedded like [Am]this.
};

export type Song = {
  id: string;
  title: string;
  artist: string;
  lyrics: LyricLine[];
  updatedAt: Date;
  originalKey?: string;
  bpm?: number;
  timeSignature?: string;
};

const songs: Song[] = [
  {
    id: '1',
    title: 'Starlight Echoes',
    artist: 'Celestial Sound',
    updatedAt: new Date('2023-10-26T10:00:00Z'),
    originalKey: 'C',
    bpm: 120,
    timeSignature: '4/4',
    lyrics: [
      { time: 0, text: "(Intro)" },
      { time: 2, text: "[Am] [G] [C] [F]" },
      { time: 6, text: "[C] [G] [Am] [F]" },
      { time: 10, text: "" },
      { time: 11, text: "[Am]In the quiet of the [G]night," },
      { time: 15, text: "A single [C]star begins to [F]glow," },
      { time: 19, text: "[C]Casting shadows in the [G]light," },
      { time: 23, text: "A silent, [Am]cosmic [F]show." },
      { time: 27, text: "" },
      { time: 28, text: "(Chorus)" },
      { time: 29, text: "We're just [C]echoes in the [G]starlight," },
      { time: 32, text: "Fading [Am]in and out of [F]view," },
      { time: 36, text: "[C]Dancing in the pale [G]moonlight," },
      { time: 40, text: "Just me and [Am]you.[F]" },
      { time: 44, text: "" },
      { time: 45, text: "(Solo)" },
      { time: 47, text: "[C] [G] [Am] [F]" },
      { time: 51, text: "[C] [G] [Am] [G]" },
      { time: 55, text: "" },
      { time: 56, text: "(Verse 2)" },
      { time: 57, text: "Across the [Am]void, a signal [G]sent," },
      { time: 60, text: "A whispered [C]word, a fleeting [F]thought," },
      { time: 64, text: "On [C]waves of ether, [G]we're content," },
      { time: 68, text: "In this [Am]vastness we are [F]caught." },
      { time: 72, text: "" },
      { time: 73, text: "(Chorus)" },
      { time: 74, text: "We're just [C]echoes in the [G]starlight," },
      { time: 77, text: "Fading [Am]in and out of [F]view," },
      { time: 81, text: "[C]Dancing in the pale [G]moonlight," },
      { time: 85, text: "Just me and [Am]you.[F]" },
      { time: 89, text: "(Outro)" },
      { time: 91, text: "[C] [G] [Am] [F]... (fade out)" },
    ],
  },
  {
    id: '2',
    title: 'Ocean Drive',
    artist: 'The Midnight Bloom',
    updatedAt: new Date('2025-07-15T10:00:00Z'),
    originalKey: 'G',
    bpm: 100,
    timeSignature: '4/4',
    lyrics: [
      { time: 5, text: "Palm trees swaying in the breeze," },
      { time: 9, text: "Neon lights are calling me," },
      { time: 13, text: "Driving down the coastal road," },
      { time: 17, text: "Lifting off a heavy load." },
      { time: 21, text: "This is the life on Ocean Drive," },
      { time: 25, text: "Feeling so completely alive," },
      { time: 29, text: "Underneath the sunset skies," },
      { time: 33, text: "Reflected in your loving eyes." },
      { time: 40, text: "The city sleeps, but we're awake," },
      { time: 44, text: "For goodness, for heaven's sake," },
      { time: 48, text: "Let's chase the dawn until it breaks," },
      { time: 52, text: "No more sorrows, no more heartaches." },
      { time: 56, text: "This is the life on Ocean Drive," },
      { time: 60, text: "Feeling so completely alive," },
      { time: 64, text: "Underneath the sunset skies," },
      { time: 68, text: "Reflected in your loving eyes." },
    ],
  },
  {
    id: '3',
    title: 'City of Dreams',
    artist: 'Urban Canvas',
    updatedAt: new Date('2023-11-30T09:00:00Z'),
    originalKey: 'Dm',
    bpm: 95,
    timeSignature: '4/4',
    lyrics: [
        { time: 4, text: "The rain is washing streets of chrome," },
        { time: 8, text: "Far away from what was home," },
        { time: 12, text: "A thousand faces pass me by," },
        { time: 16, text: "Reflected in a tearful eye." },
        { time: 20, text: "In this city of our dreams," },
        { time: 24, text: "Nothing's ever what it seems," },
        { time: 28, text: "Chasing flashing, distant gleams," },
        { time: 32, text: "Tearing at the very seams." },
        { time: 38, text: "The subway rattles, a lonely sound," },
        { time: 42, text: "Lost and never to be found," },
        { time: 46, text: "But in the pulse, a rhythm starts," },
        { time: 50, text: "Mending all the broken hearts." },
        { time: 54, text: "In this city of our dreams," },
        { time: 58, text: "Nothing's ever what it seems," },
        { time: 62, text: "Chasing flashing, distant gleams," },
        { time: 66, text: "Living out our wildest schemes." },
    ],
  },
  {
    id: '4',
    title: 'Holy Forever',
    artist: 'Chris Tomlin',
    updatedAt: new Date('2024-02-20T11:00:00Z'),
    originalKey: 'A',
    bpm: 72,
    timeSignature: '4/4',
    lyrics: [
      { time: 0, text: "(Intro)" },
      { time: 2, text: "[A] [F#m] [D] [E]" },
      { time: 6, text: "[A] [F#m] [D] [E]" },
      { time: 10, text: "" },
      { time: 11, text: "(Verse 1)" },
      { time: 12, text: "[A]A thousand generations" },
      { time: 15, text: "[F#m]Falling down in worship" },
      { time: 19, text: "[D]To sing the song of [E]ages to the [A]Lamb" },
      { time: 23, text: "" },
      { time: 24, text: "[A]And all who’ve gone before us" },
      { time: 28, text: "[F#m]And all who will believe" },
      { time: 32, text: "[D]Will sing the song of [E]ages to the [A]Lamb" },
      { time: 36, text: "" },
      { time: 37, text: "(Chorus)" },
      { time: 38, text: "Your name is the [A]highest" },
      { time: 41, text: "Your name is the [F#m]greatest" },
      { time: 45, text: "Your name stands a[D]bove them [E]all[A]" },
      { time: 49, text: "" },
      { time: 50, text: "All thrones and do[A]minions" },
      { time: 54, text: "All powers and po[F#m]sitions" },
      { time: 58, text: "Your name stands a[D]bove them [E]all[A]" },
      { time: 62, text: "" },
      { time: 63, text: "And the angels [D]cry, [A]Holy" },
      { time: 69, text: "All creation [F#m]cries, [E]Holy" },
      { time: 75, text: "You are lifted [D]high, [A]Holy" },
      { time: 81, text: "Holy for[E]ever" },
      { time: 85, text: "" },
      { time: 86, text: "(Verse 2)" },
      { time: 87, text: "[A]If you’ve been forgiven" },
      { time: 90, text: "[F#m]And if you’ve been redeemed" },
      { time: 94, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { time: 98, text: "" },
      { time: 99, text: "[A]If you’ve been delivered" },
      { time: 103, text: "[F#m]From the power of sin" },
      { time: 107, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { time: 111, text: "" },
      { time: 112, text: "(Chorus)" },
      { time: 113, text: "And the angels [D]cry, [A]Holy" },
      { time: 118, text: "All creation [F#m]cries, [E]Holy" },
      { time: 124, text: "You are lifted [D]high, [A]Holy" },
      { time: 130, text: "Holy for[E]ever" },
      { time: 134, text: "" },
      { time: 135, text: "Your name is the [A]highest" },
      { time: 139, text: "Your name is the [F#m]greatest" },
      { time: 143, text: "Your name stands a[D]bove them [E]all[A]" },
      { time: 147, text: "" },
      { time: 148, text: "All thrones and do[A]minions" },
      { time: 152, text: "All powers and po[F#m]sitions" },
      { time: 156, text: "Your name stands a[D]bove them [E]all[A]" },
      { time: 160, text: "" },
      { time: 161, text: "(Outro)" },
      { time: 162, text: "And the angels [D]cry, [A]Holy" },
      { time: 167, text: "All creation [F#m]cries, [E]Holy" },
      { time: 173, text: "You are lifted [D]high, [A]Holy" },
      { time: 179, text: "Holy for[E]ever" },
      { time: 183, text: "" },
      { time: 184, text: "Holy for[A]ever" },
    ],
  },
];

export function getSongs(): Song[] {
  return songs;
}

export function getSongById(id: string): Song | undefined {
  return songs.find((song) => song.id === id);
}
