export type LyricLine = {
  bar: number; // in seconds
  text: string; // Chords can be embedded like [Am]this.
};

export type Song = {
  id: string;
  title: string;
  artist: string;
  lyrics: LyricLine[];
  updatedAt: Date;
  originalKey?: string;
  bpm?: number;
  timeSignature?: string;
  source: 'system' | 'user'; // system: from the app, user: custom song or upload
  // Fields for user-uploaded songs
  userId?: string;
  uploaderName?: string;
  uploaderEmail?: string;
};

const songs: Song[] = [
  {
    id: '1',
    title: 'Starlight Echoes',
    artist: 'Celestial Sound',
    updatedAt: new Date('2023-10-26T10:00:00Z'),
    originalKey: 'C',
    bpm: 120,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { bar: 0, text: "(Intro)" },
      { bar: 1, text: "[Am] [G] [C] [F]" },
      { bar: 2, text: "[C] [G] [Am] [F]" },
      { bar: 3, text: "" },
      { bar: 4, text: "(Verse 1)" },
      { bar: 5, text: "[Am]In the quiet of the [G]night," },
      { bar: 6, text: "A single [C]star begins to [F]glow," },
      { bar: 7, text: "[C]Casting shadows in the [G]light," },
      { bar: 8, text: "A silent, [Am]cosmic [F]show." },
      { bar: 9, text: "" },
      { bar: 10, text: "(Chorus)" },
      { bar: 11, text: "We're just [C]echoes in the [G]starlight," },
      { bar: 12, text: "Fading [Am]in and out of [F]view," },
      { bar: 13, text: "[C]Dancing in the pale [G]moonlight," },
      { bar: 14, text: "Just me and [Am]you.[F]" },
      { bar: 15, text: "" },
      { bar: 16, text: "(Verse 2)" },
      { bar: 17, text: "Across the [Am]void, a signal [G]sent," },
      { bar: 18, text: "A whispered [C]word, a fleeting [F]thought," },
      { bar: 19, text: "On [C]waves of ether, [G]we're content," },
      { bar: 20, text: "In this [Am]vastness we are [F]caught." },
      { bar: 21, text: "" },
      { bar: 22, text: "(Chorus)" },
      { bar: 23, text: "We're just [C]echoes in the [G]starlight," },
      { bar: 24, text: "Fading [Am]in and out of [F]view," },
      { bar: 25, text: "[C]Dancing in the pale [G]moonlight," },
      { bar: 26, text: "Just me and [Am]you.[F]" },
      { bar: 27, text: "" },
      { bar: 28, text: "(Solo)" },
      { bar: 29, text: "[C] [G] [Am] [F]" },
      { bar: 30, text: "[C] [G] [Am] [G]" },
      { bar: 31, text: "" },
      { bar: 32, text: "(Outro)" },
      { bar: 33, text: "[C] [G] [Am] [F]... (fade out)" },
    ],
  },
  {
    id: '2',
    title: 'Ocean Drive',
    artist: 'The Midnight Bloom',
    updatedAt: new Date('2025-07-15T10:00:00Z'),
    originalKey: 'G',
    bpm: 100,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { bar: 0, text: "(Intro)" },
      { bar: 1, text: "[G] [D] [Em] [C]" },
      { bar: 2, text: "[G] [D] [Em] [C]" },
      { bar: 3, text: "" },
      { bar: 4, text: "(Verse 1)" },
      { bar: 5, text: "[G]Palm trees swaying in the [D]breeze," },
      { bar: 6, text: "[Em]Neon lights are [C]calling me," },
      { bar: 7, text: "[G]Driving down the [D]coastal road," },
      { bar: 8, text: "[Em]Lifting off a [C]heavy load." },
      { bar: 9, text: "" },
      { bar: 10, text: "(Chorus)" },
      { bar: 11, text: "This is the [G]life on [D]Ocean Drive," },
      { bar: 12, text: "Feeling so com[Em]pletely a[C]live," },
      { bar: 13, text: "[G]Underneath the [D]sunset skies," },
      { bar: 14, text: "Reflected [Em]in your loving [C]eyes." },
      { bar: 15, text: "" },
      { bar: 16, text: "(Verse 2)" },
      { bar: 17, text: "[G]The city sleeps, but [D]we're awake," },
      { bar: 18, text: "For [Em]goodness, for [C]heaven's sake," },
      { bar: 19, text: "[G]Let's chase the dawn un[D]til it breaks," },
      { bar: 20, text: "No more [Em]sorrows, no more [C]heartaches." },
      { bar: 21, text: "" },
      { bar: 22, text: "(Chorus)" },
      { bar: 23, text: "This is the [G]life on [D]Ocean Drive," },
      { bar: 24, text: "Feeling so com[Em]pletely a[C]live," },
      { bar: 25, text: "[G]Underneath the [D]sunset skies," },
      { bar: 26, text: "Reflected [Em]in your loving [C]eyes." },
      { bar: 27, text: "" },
      { bar: 28, text: "(Outro)" },
      { bar: 29, text: "[G] [D] [Em] [C]" },
      { bar: 30, text: "[G] [D] [Em] [C]... (fade out)" },
    ],
  },
  {
    id: '3',
    title: 'City of Dreams',
    artist: 'Urban Canvas',
    updatedAt: new Date('2023-11-30T09:00:00Z'),
    originalKey: 'Dm',
    bpm: 95,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
        { bar: 0, text: "(Verse 1)" },
        { bar: 1, text: "The [Dm]rain is washing streets of [C]chrome," },
        { bar: 2, text: "[Bb]Far away from what was [F]home," },
        { bar: 3, text: "A [Dm]thousand faces pass me [C]by," },
        { bar: 4, text: "[Bb]Reflected in a tearful [A]eye." },
        { bar: 5, text: "" },
        { bar: 6, text: "(Chorus)" },
        { bar: 7, text: "In this [Dm]city of our [C]dreams," },
        { bar: 8, text: "[Bb]Nothing's ever what it [F]seems," },
        { bar: 9, text: "[Gm]Chasing flashing, distant [Dm]gleams," },
        { bar: 10, text: "[Bb]Tearing [A]at the very [Dm]seams." },
        { bar: 11, text: "" },
        { bar: 12, text: "(Verse 2)" },
        { bar: 13, text: "The [Dm]subway rattles, a lonely [C]sound," },
        { bar: 14, text: "[Bb]Lost and never to be [F]found," },
        { bar: 15, text: "But [Dm]in the pulse, a rhythm [C]starts," },
        { bar: 16, text: "[Bb]Mending all the broken [A]hearts." },
        { bar: 17, text: "" },
        { bar: 18, text: "(Chorus)" },
        { bar: 19, text: "In this [Dm]city of our [C]dreams," },
        { bar: 20, text: "[Bb]Nothing's ever what it [F]seems," },
        { bar: 21, text: "[Gm]Chasing flashing, distant [Dm]gleams," },
        { bar: 22, text: "[Bb]Living [A]out our wildest [Dm]schemes." },
    ],
  },
  {
    id: '4',
    title: 'Holy Forever',
    artist: 'Chris Tomlin',
    updatedAt: new Date('2024-02-20T11:00:00Z'),
    originalKey: 'A',
    bpm: 72,
    timeSignature: '4/4',
    source: 'system',
    lyrics: [
      { bar: 0, text: "(Intro)" },
      { bar: 1, text: "[A] [F#m] [D] [E]" },
      { bar: 2, text: "[A] [F#m] [D] [E]" },
      { bar: 3, text: "" },
      { bar: 4, text: "(Verse 1)" },
      { bar: 5, text: "[A]A thousand generations" },
      { bar: 6, text: "[F#m]Falling down in worship" },
      { bar: 7, text: "To [D]sing the song of [E]ages to the [A]Lamb" },
      { bar: 8, text: "" },
      { bar: 9, text: "[A]And all who’ve gone before us" },
      { bar: 10, text: "And [F#m]all who will believe" },
      { bar: 11, text: "Will [D]sing the song of [E]ages to the [A]Lamb" },
      { bar: 12, text: "" },
      { bar: 13, text: "(Chorus)" },
      { bar: 14, text: "Your name is the [A]highest" },
      { bar: 15, text: "Your name is the [F#m]greatest" },
      { bar: 16, text: "Your name stands a[D]bove them [E]all[A]" },
      { bar: 17, text: "All thrones and do[A]minions" },
      { bar: 18, text: "All powers and po[F#m]sitions" },
      { bar: 19, text: "Your name stands a[D]bove them [E]all[A]" },
      { bar: 20, text: "" },
      { bar: 21, text: "(Bridge)" },
      { bar: 22, text: "And the angels [D]cry, [A]Holy" },
      { bar: 23, text: "All creation [F#m]cries, [E]Holy" },
      { bar: 24, text: "You are lifted [D]high, [A]Holy" },
      { bar: 25, text: "Holy for[E]ever" },
      { bar: 26, text: "" },
      { bar: 27, text: "(Verse 2)" },
      { bar: 28, text: "[A]If you’ve been forgiven" },
      { bar: 29, text: "And [F#m]if you’ve been redeemed" },
      { bar: 30, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { bar: 31, text: "" },
      { bar: 32, text: "[A]If you’ve been delivered" },
      { bar: 33, text: "From the [F#m]power of sin" },
      { bar: 34, text: "[D]Sing the song of [E]ages to the [A]Lamb" },
      { bar: 35, text: "" },
      { bar: 36, text: "(Chorus)" },
      { bar: 37, text: "Your name is the [A]highest" },
      { bar: 38, text: "Your name is the [F#m]greatest" },
      { bar: 39, text: "Your name stands a[D]bove them [E]all[A]" },
      { bar: 40, text: "All thrones and do[A]minions" },
      { bar: 41, text: "All powers and po[F#m]sitions" },
      { bar: 42, text: "Your name stands a[D]bove them [E]all[A]" },
      { bar: 43, text: "" },
      { bar: 44, text: "(Bridge)" },
      { bar: 45, text: "And the angels [D]cry, [A]Holy" },
      { bar: 46, text: "All creation [F#m]cries, [E]Holy" },
      { bar: 47, text: "You are lifted [D]high, [A]Holy" },
      { bar: 48, text: "Holy for[E]ever" },
      { bar: 49, text: "" },
      { bar: 50, text: "(Outro)" },
      { bar: 51, text: "Holy for[A]ever" },
    ],
  },
];

export function getSongs(): Song[] {
  return songs;
}

export function getSongById(id: string): Song | undefined {
  return songs.find((song) => song.id === id);
}
