// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "welcome": {
    "title": "ยินดีต้อนรับสู่ LyricSync",
    "titleBack": "ยินดีต้อนรับกลับสู่ LyricSync",
    "guest": "คุณกำลังใช้งานโหมด Guest",
    "signIn": "ลงชื่อเข้าใช้เพื่อบันทึกเซ็ตลิสต์และปลดล็อกฟีเจอร์ทั้งหมด!",
    "unlock": "ปลดล็อกทุกฟีเจอร์",
    "getStarted": "เริ่มต้นใช้งาน",
    "learnMore": "ดูรายละเอียด",
    "mySetlists": "เซ็ตลิสต์ของฉัน",
    "myLibrary": "ไลบรารีของฉัน",
    "desc": "แอปสำหรับซิงค์เนื้อเพลง สร้างเซ็ตลิสต์ แชร์เพลง และใช้งานแบบออฟไลน์ได้ทุกที่ ทุกกลุ่ม ทุกศาสนา",
    "descShort": "แอปสำหรับซิงค์เนื้อเพลง สร้างเซ็ตลิสต์ แชร์เพลง และใช้งานแบบออฟไลน์ได้ทุกที่",
    "forEveryone": "ไม่จำกัดแนวเพลงหรือศาสนา"
  },
  "login": "เข้าสู่ระบบ",
  "logout": "ออกจากระบบ",
  "profile": "โปรไฟล์",
  "library": "คลังเพลง",
  "setlists": "เซ็ทลิสต์",
  "songs": "เพลง",
  "create": "สร้าง",
  "edit": "แก้ไข",
  "save": "บันทึก",
  "cancel": "ยกเลิก",
  "search": "ค้นหา",
  "premium": "พรีเมียม",
  "admin": "แอดมิน",
  "userUploads": "อัปโหลดของผู้ใช้",
  "lyrics": "เนื้อเพลง",
  "shared": "แชร์",
  "songEditor": "แก้ไขเพลง",
  "footerText": "สงวนลิขสิทธิ์ทั้งหมด",
  "thai": "ไทย",
  "english": "อังกฤษ",
  "recommendedSongs": "เพลงแนะนำ"
};
export default messages;